### ISSUE TITLE
Errors on Build

### ISSUE THREAD

**Issue by adambattenburg** [zowe/zlux-editor#7]
When trying to build using `npm run start`, I get the error `Cannot find module 'webpack/bin/config-yargs'`. In order to fix this I updated the `webpack-dev-server` to latest. 

However, I run into another error where the `./src` directory can't be found. This seems to be an issue with the Angular CLI (which is version 1.7.4), but updating to current doesn't fix the issue. After updating, I've deleted node_modules and lock files before reinstalling but didn't have any luck.

**Comment by 1000TurquoisePogs** [comment]
A change was just put in to update and trim the libraries we were using(https://github.com/zowe/zlux-editor/commit/d43491cd46c52afffcb9e1a69e2c2fa34971db71). Due to angular cli, we still can't build this repo on the mainframe, but it should build and `npm run start` should run better now. Let me know if this is still a problem.
